blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>', views.detail, name='detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from pathlib import Path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/')
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project (models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    # returns the title name in sql table instead if object

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_list_or_404, render, get_object_or_404
from .models import Blog
# Create your views here.


def all_blogs(request):
    Blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': Blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% comment %} {%block content %}
 <h2>Total Blog{{ blogs.count | pluralize}} : {{ blogs.count }}</h2>
{% for blog in blogs %}

    <a href = "{% url 'blog:detail' blog.id %}">{{ blog.title }}</a><br>
    <img src = '{{ blog.image.url }}'><br><br>
        {{ blog.description |striptags | truncatechars:100 }}<br>

    <h5>{{ blog.date }} </h5><br><br>

{% endfor %}
{%endblock%} {% endcomment %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Total Blog{{ blogs.count | pluralize}} : {{ blogs.count }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
<img src = '{{ blog.image.url }}' height = 400; width = 700> <br><br>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% comment %} {%block content %}
<h1>{{ blog.title }}</h1>
<h2>--{{ blog.date }}--</h2>
<img src = '{{ blog.image.url }}' height = 600; width = 1500>
<p>{{ blog.description }}</p>
{%endblock%}

{% extends "portfolio/base.html" %}

{% load static %} {% endcomment %}

{% block content %}

<h2 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h2>

<h5 class="text-left text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

<img src = '{{ blog.image.url }}' height = 400; width = 800> <br><br>

<p>{{ blog.description }}</p>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'portfolio/k.png' %}">

  <title>Kashish Chaurasia</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/k.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Kashish Chaurasia</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/KashishChaurasiaResume2.0.pdf' %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/kashish-chaurasia/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://gitlab.com/kashish10" target="_blank">Git</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

</body>

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
  <p><i><b>Thank You, that's all !</b></i></p>
  <p>Email :kashish.chaurasia10@gmail.com <br>Contact :8290784910</p
  >
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
        <img src ='{%  static "portfolio/kashish.png" %}' class="rounded mx-auto d-block" >

  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h3 id="hometext" class="font-weight-bold">Kashish Chaurasia is a develoepr at Dataphi Labs and lives in Bangalore</h3>
  </div>
</div>

<h2 class="mt-5">Work Experience</h2>
<hr>
<div class="row">
<br>
    <div class="card mb-3 border-0" style="max-width: 540px;">
    <div class="row g-8">
        <div class="col-md-4">
        <img src='{%  static "portfolio/dl.png" %}' class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
         <div class="card-body">
            <h5 class="card-title">Dataphi Labs</h5>
            <p class="card-text">Fullstack Developer</p>
            <p class="card-text"><small class="text-muted">2019-present (2 years +)</small></p>
        </div>
        <div class="card-body">
            <p class="card-text">Fullstack Intern</p>
            <p class="card-text"><small class="text-muted">2019 (6 Months Internship)</small></p>
        </div>
        </div>
    </div>
    </div>


    <div class="card mb-4 border-0" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src='{%  static "portfolio/nic.png" %}' class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">National Informatics Centre</h5>
        <p class="card-text">Java Intern</p>
        <p class="card-text"><small class="text-muted">2020 (2 months intership)</small></p>
      </div>
    </div>
  </div>
  </div>
</div>

<h2 class="mt-5">Education</h2>
<hr>
<div class="row">
<br>
    <div class="card mb-3 border-0" style="max-width: 540px;">
    <div class="row g-8">
        <div class="col-md-4">
        <img src='{%  static "portfolio/niit.png" %}' class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">NIIT University</h5>
            <p class="card-text">BTech. Computer Science</p>
            <p class="card-text">8.1 CGPA</p>
            <p class="card-text"><small class="text-muted">2015-19</small></p>
        </div>
        </div>
    </div>
    </div>

    <div class="card mb-4 border-0" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src='{%  static "portfolio/dps.png" %}' class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Delhi Public School, Sushantlok</h5>
        <p class="card-text">CBSE Boards</p>
        <p class="card-text">Class X : 10 CGPA</p>
        <p class="card-text">Class XII : 84%</p>
        <p class="card-text"><small class="text-muted">2013-2015</small></p>
      </div>
    </div>
  </div>
  </div>
</div>

<h2 class="mt-5">Skills</h2>
<hr>
<div class="row">
  <a class="btn btn-light me-2"  role="button">Python <i class="fab fa-github ms-2"></i></a>
    <a class="btn btn-light me-2"  role="button">Django <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Php <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Sql <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Git <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Rest APIs <i class="fab fa-github ms-2"></i></a>
    <a class="btn btn-light me-2"  role="button">Django Rest Framework <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">html/css <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Bootstrap <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Javascript <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Opencart <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Frappe <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Moodle <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Web Intelligence <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Information Retrieval <i class="fab fa-github ms-2"></i></a>
  <a class="btn btn-light me-2"  role="button">Data Structures & Algorithms<i class="fab fa-github ms-2"></i></a>

</div>

<h2 class="mt-5">Projects</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>
<hr>
{% endblock %}